<ul class="list-unstyled" style="">
          <li class="review-content thumbnail" style="border: 0px solid green; overflow: hidden">
                    <div class="row">
                    <div class="col-md-8 col-md-offset-1">
                         <p class="bold"><?=$this->name ?> (<?=$this->city ?>)</p>
                         <?=$this->application ?>
                    </div>
                    <?php if(!empty($this->breed['file_path'])){ ?>
                    <div class="col-md-2 center">
                        <a href="<?=$this->url('app/breed/breed-slug', array('slug' => $this->breed['slug']))?>" class="">
                         <img src="<?=$this->breed['file_path']?>" alt="" class="img-responsive img-thumbnail">
                        </a>
                        <a href="<?=$this->url('app/breed/breed-slug', array('slug' => $this->breed['slug']))?>" class="">
                              <?=$this->breed['rus_title'] ?>
                         </a>
                    </div>
                    <?php } ?>
                    </div>
              <?php
              if($this->products)
              {
                  ?>
                  <div class="col-md-11 col-md-offset-1">
                      <?php foreach ($this->products as $product) { ?>
                          <a href="<?=$this->url('app/product', array('slug' =>
                              $product['slug'])) ?>">#<?=$product['tag']?></a> <?php
                      } ?>
                  </div>
                  <?php
              }
              ?>
          </li>
</ul>

