 <?php
 $title = 'Добавить продукт';
 $this->headTitle($title);
 ?>
 <div class="row-fluid">
 <?php 
 $form->setAttribute('action', $this->url("app/backoffice/product/add"));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-6 col-md-offset-1">
 <?php
 //echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('eng_title'));
 echo $this->formRow($form->get('rus_title'));
 echo $this->formRow($form->get('slug'));
 echo $this->formRow($form->get('tag'));
 echo $this->formRow($form->get('category'));
 echo $this->formRow($form->get('line'));
 echo $this->formRow($form->get('preview'));
 echo $this->formRow($form->get('vantage'));
 echo $this->formRow($form->get('card_text'));
 echo $this->formRow($form->get('application'));
 echo $this->formRow($form->get('ingredients'));
 ?>
 </div>
 <div class="col-md-3 col-md-offset-1">
 <div class="left-edit-menu" style="">
 <?php 
 echo $this->formRow($form->get('sort_order'));
 echo $this->formRow($form->get('active'));
 echo $this->formRow($form->get('in_stock'));
 ?>
 <div class="submit">
 <?php
 echo $this->formSubmit($form->get('submit'));
 ?>
 </div>
 </div>
 </div>
 <?php  echo $this->form()->closeTag(); ?>
 </div>