 <?php
 $title = 'Редактировать продукт';
 $this->headTitle($title);
 echo "Bread start<br>";
 echo $this->navigation('admin-nav')->breadcrumbs();
 echo "Bread ends<br>";

 ?>
 <style>
	.left-edit-menu
	{
		padding: 15px 10px;
		/*position: fixed;*/
		-webkit-box-shadow: 0px 3px 5px 0px rgba(50, 50, 50, 0.75);
		-moz-box-shadow:    0px 3px 5px 0px rgba(50, 50, 50, 0.75);
		box-shadow:         0px 3px 5px 0px rgba(50, 50, 50, 0.75);
	}
	.left-edit-menu div.submit
	{
		text-align: center;
		margin: 20px auto 0;
	}
	.left-edit-menu div.checkbox
	{
		margin: 10px auto;
	}
 </style>
 <ul class="breadcrumb">
    <li><a href="/admin">Home</a></li>
    <li><a href="/admin/product">Список продуктов</a></li>
    <li><a href="#"><?=$this->product->getCategory()->getTitle()?></a></li>
    <li class="active"><?=$this->product->getEngTitle()?></li>
</ul>
 <div class="row-fluid">
 <?php
 $form->setAttribute('action', $this->url("app/backoffice/product/id", array('id'=>$id)));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-6 col-md-offset-1">
 <?php
 //echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('eng_title'));
 echo $this->formRow($form->get('rus_title'));
 echo $this->formRow($form->get('slug'));
 echo $this->formRow($form->get('tag'));
 echo $this->formRow($form->get('category'));
 echo $this->formRow($form->get('line'));
 echo $this->formRow($form->get('preview'));
 echo $this->formRow($form->get('vantage'));
 echo $this->formRow($form->get('card_text'));
 echo $this->formRow($form->get('application'));
 echo $this->formRow($form->get('ingredients'));
 ?>
 </div>
 <div class="col-md-3 col-md-offset-1">
 <div class="left-edit-menu" style="">
 <?php
 echo $this->formRow($form->get('sort_order'));
 echo $this->formRow($form->get('active'));
 echo $this->formRow($form->get('in_stock'));
 ?>
 <div class="submit">
 <?php
 echo $this->formSubmit($form->get('submit'));
 ?>
 </div>
 </div>
 </div>
 <?php  echo $this->form()->closeTag(); ?>
 </div>