<div class="col-md-8 col-md-offset-3">
    <h1><?php echo $this->escapeHtml("Решение проблемы"); ?></h1>
    <?php
    $solutionProductForm->prepare();
    echo $this->form()->openTag($solutionProductForm);
    ?>
    <?php
    echo $this->formRow($solutionProductForm->get('product'));
    echo $this->formSubmit($solutionProductForm->get('submit'));
    ?>
    <?php  echo $this->form()->closeTag(); ?>
</div>