<div class="container">
<?php
$reviewForm->prepare();
echo $this->form()->openTag($reviewForm);
echo $this->formRow($reviewForm->get('breed'));
echo $this->formRow($reviewForm->get('name'));
echo $this->formRow($reviewForm->get('email'));
echo $this->formRow($reviewForm->get('phone'));
echo $this->formRow($reviewForm->get('city_entered'));
echo $this->formRow($reviewForm->get('review'));
echo $this->formRow($reviewForm->get('product'));
echo $this->formRow($reviewForm->get('submit'));

echo $this->form()->closeTag();
?>
</div>
