<?php
// File: upload-form.phtml
$form->setAttribute('action', $this->url("app/backoffice/product/id/image/add", array("id"=>$this->productId)));
$form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>
<div class="form-element" style="text-align: center; padding: 15px; margin: 20px auto; border: 1px dotted gray;">
    <?php $fileElement = $form->get('image-file'); ?>
    <span class="glyphicon glyphicon-picture"></span>
    <?php echo $this->formFile($fileElement); ?>
    <?php echo $this->formElementErrors($fileElement); ?>
    <?php  echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>

<?php
//$productFiles = $this->Product->getFile();
//var_dump($this->productFiles);
if(is_array($productFiles) && $productFiles){
    ?>
    <table class="table table-hover table-striped table-bordered" style="margin: 50px auto;">
    <thead>
    <tr>
        <td colspan="6" style="background-color: #101010; color: #fff; text-align:center; font-size: 120%;">Загруженные фото</td>
    </tr>
    <tr style="font-weight: bold;">
        <td>Фото</td>
        <td>Порядок</td>
        <td>Описание</td>
        <td>Редактирование</td>
        <td>Удаление</td>
    </tr>
    </thead>
    <?php
    foreach ($productFiles as $productFile) {
        ?>
        <tr>
            <td>
                <img src="<?=$productFile['src_small'] ?>" alt="">
            </td>
            <td><?=$productFile['sort']?></td>
            <td>
                <?php if(isset($productFile['description'])): ?>
                    <?=$productFile['description']?>
                <?php endif; ?>
            </td>
            <td><a data-id="<?=$productFile['id']?>" href="<?=$this->url("app/backoffice/image", array("id"=>$productFile['id']))?>" class="btn btn-danger edit-link" target="_blank">Редактировать</a>
                <div id="modal-<?=$productFile['id']?>" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Confirmation</h4>
                            </div>
                            <div class="modal-body">
                                <p>Do you want to save changes you made to document before closing?</p>
                                <p class="text-warning"><small>If you don't save, your changes will be lost.</small></p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td><a href="<?=$this->url("app/backoffice/image/delete", array("id"=>$productFile['id']))?>" class="btn btn-success" target="_blank">Удалить</a></td>
        </tr>
        <?php
    }
    ?></table><?php
}
?>
<script type="text/javascript">
    $(document).ready(function(){
        $(".edit-link").on("click", function (event) {
            event.preventDefault();

            var dataId = $(this).attr("data-id");
            $('#modal-'+dataId).modal('show');
            console.log("#modal"+dataId);
        })
    });
</script>

