<div class="col-md-10 col-md-offset-1">
 <?php 
 $form->setAttribute('action', $this->url('app/backoffice/content/id/delete', array('id' => $this->content->getId())));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml("Удалить ".$this->content->getName()); ?></h1>
  <?php 
 		echo $this->formSubmit($form->get('confirm-no'));
		echo $this->formSubmit($form->get('confirm-yes'));
  ?>
 <?php  echo $this->form()->closeTag(); ?>
 </div>