<?php
$this->ButtonHelper()->showAddButton($this->url('app/admin-info-block/add'), "Добавить материал инфоблока");
?>
    <h1 class="center">Список материалов инфоблока</h1>
<?php
if(is_array($infoBlocks))
{
    ?>
    <table class="table-hover table-stripted table">
        <thead>
        <tr class="bold">
            <td>Заголовок материала</td>
            <td>Сниппет</td>
            <td>Администрирование</td>
        </tr>
        </thead>
        <?php foreach ($infoBlocks as $material){ ?>
            <tr>
                <td><?=$material->getHeader() ?></td>
                <td><?=$material->getSnippet() ?></td>
                <td><a class="btn btn-success" href="<?=$this->url('app/admin-info-block/edit', array('id' => $material->getId())); ?>">Редактировать</a></td>
            </tr>
        <?php } ?>

    </table>
    <?php
}