<div class="row-fluid">
 <?php 
 $form->setAttribute('action', $this->url('app/backoffice/category/id', array('id' => $this->id, )));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml("Редактировать категорию"); ?></h1>
<div class="col-md-6 col-md-offset-1">
 <?php
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('slug'));
 echo $this->formRow($form->get('info_block'));
 echo $this->formSubmit($form->get('submit'));

 ?>
 </div>
 <?php  echo $this->form()->closeTag(); ?>
 </div>