<?php
$this->headTitle('Купить косметику для собак Isle of Dogs');
echo $this->partial('partial/sidebar/left-sidebar');?>
<div class="col-md-9">
    <div class="buy">
        <h2 class="center">Оптовые закупки</h2>
        <h3 class="center">Работаем с оптовиками, грумерами  и питомниками</h3>
        <ul class="list-unstyled list-inline center">
            <li>
                <span class="glyphicon glyphicon-phone"></span> <a href="tel:79037926112">+7(903)792-6112</a>
            </li>
            <li>
                <a href="mailto:shop@isleofdogs.ru"><span class="glyphicon glyphicon-envelope"></span> shop@isleofdogs.ru</a>
            </li>
        </ul>
    </div>
    <hr>
    <h1 class="center">Розничные закупки</h1>
<?php
echo $this->partial('partial/site/content/buy');
?>
    <hr>
    <div class="">
<h3 class="center">Представительства в регионах</h3>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Екатеринбург</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Олеся Коновалова</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+73433459599">+7(343)345-95-99</a></dd>
    </dl>

     <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Киров</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>ИП Синицын Л.Г.</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79058716727">+7(905)871-67-27</a></dd>
        <dd><a href="tel:+79058715549">+7(905)871-55-49</a></dd>
        <dt><span class="glyphicon glyphicon-envelope"></span></dt>
         <dd><a href="mailto:ptici@mail.ru ">ptici@mail.ru</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Москва</dd>
        <dt><span class="glyphicon glyphicon-info-sign"></span></dt>
        <dd>ООО Торговая компания «Зоомикс»</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+74991275613">+7(499)127-56-13</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Находка</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Есина Мария</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79025258691">+7(902)525-86-91</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Нижний Новгород</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Дедина Татьяна</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79616369002">+7(961)636-90-02</a></dd>
        <dd><a href="tel:+79040514570">+7(904)051-45-70</a></dd>
        <dt><span class="glyphicon glyphicon-envelope"></span></dt>
        <dd><a href="mailto:dedina77@mail.ru ">dedina77@mail.ru</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Новокузнецк</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Елена Зыкова</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79039096435">+7(903)909-64-35</a></dd>
    </dl>
    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Пермь</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Алёна Малинина</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79194970414">+7(919)497-04-14</a></dd>
        <dt><span class="glyphicon glyphicon-envelope"></span></dt>
        <dd><a href="mailto:malininaalena@mail.ru">malininaalena@mail.ru</a></dd>
        <dt><span class="glyphicon glyphicon-link"></span></dt>
        <dd><a href="http://shop.dog59.ru/" target="_blank">http://shop.dog59.ru/</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Санкт-Петербург</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Евгений Батяев</dd>
        <dt><span class="glyphicon glyphicon-link"></span></dt>
        <dd><a href="https://vk.com/iodspb" target="_blank">vk.com/iodspb</a></dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79117758075">+7(911)26-26-126</a></dd>
        <dt><span class="glyphicon glyphicon-envelope"></span></dt>
        <dd><a href="mailto:iodspb@yandex.ru">iodspb@yandex.ru</a></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Саратов</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Ольга Викторова</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79271558456">+7(927)155-84-56</a></dd>
        <dd><a href="tel:+78452464562">+7(8452)46-45-62</a></dd>
    </dl>

</div>
</div>