<?php
$this->headTitle('Купить косметику для собак Isle of Dogs');
echo $this->partial('partial/sidebar/left-sidebar');?>
<div class="col-md-9">
    <div class="buy">
        <h2 class="center">Оптовые закупки</h2>
        <h3 class="center">Работаем с оптовиками, грумерами  и питомниками</h3>
        <ul class="list-unstyled list-inline center">
            <li>
                <span class="glyphicon glyphicon-phone"></span> <a href="tel:79037926112">+7(903)792-6112</a>
            </li>
            <li>
                <a href="mailto:shop@isleofdogs.ru"><span class="glyphicon glyphicon-envelope"></span> shop@isleofdogs.ru</a>
            </li>
        </ul>
    </div>
    <hr>
    <h1 class="center">Розничные закупки</h1>
<?php
echo $this->partial('partial/site/content/buy');
?>
    <hr>
    <div class="">
<h3 class="center">Представительство в регионах</h3>


    <dl class="dl-horizontal">
        <dt><span class="glyphicon glyphicon-map-marker"></span></dt>
        <dd>Пермь</dd>
        <dt><span class="glyphicon glyphicon-user"></span></dt>
        <dd>Алёна Малинина</dd>
        <dt><span class="glyphicon glyphicon-phone"></span></dt>
        <dd><a href="tel:+79194970414">+7(919)497-04-14</a></dd>
        <dt><span class="glyphicon glyphicon-envelope"></span></dt>
        <dd><a href="mailto:malininaalena@mail.ru">malininaalena@mail.ru</a></dd>
        <dt><span class="glyphicon glyphicon-link"></span></dt>
        <dd><a href="http://shop.dog59.ru/" target="_blank">http://shop.dog59.ru/</a></dd>
    </dl>

</div>
</div>