<?php
$this->headTitle('Контакты');
?>
<div class="container contacts">
<?php
//    echo $this->partial('partial/site/large-logo');
?>
    <h1 class="center contacts__header">Дистрибьютерский центр косметики Isle of Dogs в России</h1>
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-callout bs-callout-info">
            <h4>Сотрудничество</h4>
            <p>Наша компания заинтересована в развитии стабильных и перспективных партнерских отношений с компаниями, занятыми в сфере продаж товаров для животных. Основная задача сотрудничества - продвижение продукции фирмы Isle Of Dogs в регионах. Вся продукция сертифицирована.</p>
            <p>Предлагаем оптовые поставки на выгодных условиях. Индивидуальный подход к каждому клиенту. Оптовые цены обсуждаемы в зависимости от размера покупки. В случае тесного сотрудничества готовы сделать особое предложение. Мы готовы сотрудничать с любой организацией, ведущей бизнес на территории Российской Федерации.</p>
        </div>
    </div>
    <div class="col-md-5 contacts__info_container">
        <img src="https://s3.eu-central-1.amazonaws.com/iodogs/src/iodogs-logo-screen.png" alt="" class="img-responsive contacts__logo">
        <ul>
            <li><span class="glyphicon glyphicon-phone-alt"></span> <a href="tel:79037926112">+7(903)792-61-12</a></li>
            <li><span class="glyphicon glyphicon-envelope"></span> <a href="mailto:shop@isleofdogs.ru"> shop@isleofdogs.ru</a></li>
            <li><span class="glyphicon glyphicon-question-sign"></span> Если у вас возникли вопросы, заполните пожалуйста форму обратной связи и мы оперативно ответим вам.</li>
        </ul>
        <?php
//        echo $this->partial('partial/social/vk');
        ?>
    </div>
    <div class="col-md-6 contacts__form_container">
        <?php
        //echo $this->partial('partial/forms/contacts', array('form' => $contactsForm));
        ?>
    </div>

</div>