<?php
$this->headTitle($page['title']);
$this->headMeta($page['snippet'], "description");
$this->headMeta($page['keywords'], "keywords");
//$this->headMeta("test description text", "twitter:domain");
//$this->headMeta()->setProperty('og:title', 'my article title');
?>
<div class="">
<?php
    echo $this->partial('partial/sidebar/left-sidebar');
?>
    <div style="overflow: hidden">
    <blockquote class="pull-right" style="width:70%; overflow: hidden; text-align: right">
        <span class="italic">«<?=$page['aphorism']['content']?>»</span>
        <br><?=$page['aphorism']['author']?>
    </blockquote>
    </div>
    <div class="col-md-9">
        <h1 class="center"><?=$page['header'];?></h1>
        <?php
        echo $page['content'];
        ?>
    </div>
</div>