<div class="jumbotron">
    <?php
    $this->loginForm->setAttribute('action', $this->url('login'));
    $this->loginForm->prepare();
    echo $this->form()->openTag($this->loginForm);
    echo $this->formRow($this->loginForm->get("user_name"));
    echo $this->formRow($this->loginForm->get("password"));
    //echo $this->formCaptcha($loginForm->get("captcha"));
    echo $this->formRow($this->loginForm->get("csrf"));
    echo $this->formRow($this->loginForm->get("submit"));
    echo $this->form()->closeTag();
    ?>
    <?php if ($this->message): ?>
        <div class="text-warning"><?=$this->message ?></div>
    <?php endif; ?>
</div>
