<ul class="col-md-4 col-md-offset-0 list-unstyled">
     <li class="">
          <div style="background: url(/breeds/yorkshire-terrier.jpg) no-repeat center center; background-size: 50px 50px; width: 75px; margin: auto;">
          <img style="margin: auto;" src="/img/empty-circle-150.png" class="img-responsive" alt="">
          </div>
     </li>
     <li style="text-align: center;"><?=$this->breed ?></li>
     <li class="review-content"><?=$this->review ?></li>
     <li style="text-align: right;">--<?=$this->name ?> (<?=$this->city ?>)</li>
     </ul>