<h3 style="font-size:80%; border: 0px solid black; color:rgb(194, 82, 52); display: none;">Поделитесь, чтобы не потерять</h3>
<div class="social-likes subscribe_social pull-right" style="margin: 5px auto 20px; text-align: right;">
<div style="font-size: 20px;
    height: 30px;
    line-height: 1.5;
    color: #EDEDED;
    vertical-align: middle;" class="glyphicon glyphicon-heart hidden"></div>
<div class="vkontakte social-likes_notext" title="Поделиться ссылкой во Вконтакте"></div>
<div class="facebook social-likes_notext" title="Поделиться ссылкой на Фейсбуке"></div>

 <div class="">
    <span class="label label-default">
    <span class="glyphicon glyphicon-heart"></span> 
    Поделиться, чтобы не потерять
    </span>
</div>

</div>


