<div class="container-fluid bg1">
<div class="jumbotron">
<div class="col-md-6">
<a href=""><img src="http://iodogs.local/upload/5a4a059cb581ea27e0f52881f627ac3b1457691993.jpg" class="img-responsive" alt=""></a>
</div>
<div class="col-md-6">
	<a href="http://petgear.ru/catalog/groom/cosmetic/Isleofdogs/shampoo/shampoo_477.html" target="_blank" class="btn btn-success">Купить сейчас</a>
	<div class="input-group">
  <span class="input-group-addon" id="basic-addon1">@</span>
  <input type="text" class="form-control" placeholder="Email" aria-describedby="basic-addon1">
</div>
</div>
</div>
</div>
