<div class="buy">
    <h2 class="center">Интернет Магазин «PETGEAR»</h2>
    <h3 class="center">доставка по Москве, отправка в регионы</h3>
    <ul class="list-unstyled list-inline center">
        <li>
            <a class="btn btn-success" href="http://petgear.ru/catalog/groom/cosmetic/Isleofdogs/" target="_blank"><span class="glyphicon glyphicon-shopping-cart"></span> Перейти в магазин</a></li>
        <li>
            <a class="btn btn-default" href="http://petgear.ru/payment/" target="_blank"><span class="glyphicon glyphicon-info-sign"></span> Доставка и оплата</a></li>
    </ul>
</div>