<div class="col-md-10 col-md-offset-1">
    <img src="<?=$src['src_small']?>" alt="">
    <?php
    //print_r($confirmForm);
    
    $confirmForm->setAttribute('action', $this->url('app/backoffice/image/delete', array('id' => $this->file->getId())));
    $confirmForm->prepare();
    echo $this->form()->openTag($confirmForm);
    ?>
    <h1 style="text-align:center;"><?php echo $this->escapeHtml("Удалить Файл"); ?></h1>
    <?php
    echo $this->formSubmit($confirmForm->get('confirm-no'));
    echo $this->formSubmit($confirmForm->get('confirm-yes'));
    ?>
    <?php  echo $this->form()->closeTag(); ?>
    <?php
   
    ?>
</div>