<div class="row-fluid">
    <?php
    $imageEditForm->setAttribute('action', $this->url('app/admin-image', array('id' => $this->file['id'], )));
    $imageEditForm->prepare();
    echo $this->form()->openTag($imageEditForm);
    ?>
    <h1 style="text-align:center;"><?php echo $this->escapeHtml("Изменение файла"); ?></h1>
    <img src="<?=$file['src_small']?>" alt="">
    <div class="col-md-6 col-md-offset-1">
        <?php
        echo $this->formRow($imageEditForm->get('sort_order'));
        echo $this->formRow($imageEditForm->get('description'));
        echo $this->formSubmit($imageEditForm->get('submit'));

        ?>
    </div>
    <?php  echo $this->form()->closeTag(); ?>
</div>