<div class="jumbotron">
    <h1 class="text-center">Загрузка изображений</h1>
    <?php
    $this->form->setAttribute('action', $this->url("app/backoffice/image/upload"));
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    echo $this->formFile($this->form->get('image_file'));
    echo $this->formSubmit($this->form->get('submit'));
    echo $this->form()->closeTag();
    ?>
    <?php if ($this->messages): ?>
        <div class="text-danger">
            <ul class="list-unstyled">
                <?php foreach ($this->messages['image_file'] as $message): ?>
                    <li><?=$message?></li>
                <?php endforeach;?>
            </ul>
        </div>
    <?php endif;?>
</div>
<div class="row" style="margin: auto">
    <?php
    if ($this->images)
    {
        /** @var \IodogsDoctrine\Entity\ImageStorage $image */
        foreach ($this->images as $image) {
            ?>
            <div class="col-sm-3" style="margin: 30px auto; padding: 10px;">
                <a href="<?=$image->getS3FilePath()?>" target="_blank">
                    <img class="img-responsive img-rounded" style="border: 1px solid #7e64ff; max-height: 150px; margin: auto" src="<?=$image->getS3SmallFilePath()?>" alt="">
                </a>
            </div>
            <?php
        }
    }
    ?>
</div>