<div class="col-md-8 col-md-offset-3">
    <h1><?php echo $this->escapeHtml("Добавить проблему"); ?></h1>
    <?php
    $solutionForm->setAttribute('action', $this->url('app/backoffice/solution/edit', array('id' => $solution->getId())));
    $solutionForm->prepare();
    echo $this->form()->openTag($solutionForm);
    ?>
    <?php
    echo $this->formRow($solutionForm->get('title'));
    echo $this->formRow($solutionForm->get('slug'));
    echo $this->formRow($solutionForm->get('info_block'));
    echo $this->formRow($solutionForm->get('img_path'));
    echo $this->formSubmit($solutionForm->get('submit'));
    ?>
    <?php  echo $this->form()->closeTag(); ?>
</div>
<?php
$solutionProductForm->setAttribute('action', $this->url('app/backoffice/solution/edit/product', array('id' => $solution->getId())));
echo $this->partial('partial/forms/product-solution', array('solutionProductForm' => $solutionProductForm));
?>