<div class="col-md-8 col-md-offset-3">
 <?php 
 //$form->setAttribute('action', "content".$this->id);
 $form->setAttribute('action', $this->url('app/backoffice/line/add'));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml("Добавить линию"); ?></h1>
  <?php 
  echo $this->formRow($form->get('title'));
  echo $this->formRow($form->get('slug'));
  echo $this->formRow($form->get('info_block'));
  echo $this->formRow($form->get('img_path'));
  echo $this->formSubmit($form->get('submit'));
  ?>
 <?php  echo $this->form()->closeTag(); ?>
 </div>