<div class="col-md-10 col-md-offset-1">
 <?php 
 //$form->setAttribute('action', "content".$this->id);
 $form->setAttribute('action', $this->url('app/backoffice/line/id', array('lineId' => $this->line->getId())));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
  <h1 style="text-align:center;"><?php echo $this->escapeHtml("Редактировать ".$this->line->getTitle()); ?></h1>
  <?php 
  echo $this->formRow($form->get('title'));
  echo $this->formRow($form->get('slug'));
  echo $this->formRow($form->get('info_block'));
  echo $this->formRow($form->get('img_path'));
  echo $this->formSubmit($form->get('submit'));
  ?>
 <?php  echo $this->form()->closeTag(); ?>
 </div>