<?php
if(is_array($this->lines)){
    ?>
    <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <?php
            $active = true;

            foreach ($this->lines as $line)
            {
                ?>
                <div class="item <?php if($active) echo "active" ?>">
                    <a href="<?=$this->url('app/line/slug', array('slug' => $line['slug']))?>">
                        <img src="<?=$line['img_path']?>" alt="<?=$line['title']?>" class="img-responsive mauto">
                    </a>
                </div>
                <?php
                if($active) $active = false;
            }
            ?>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    <?php
}
?>